задача 1 модуль7
js-tasks-ru/jsbasic-20240219_vitalaa547 pull request #12
Opened 2024-03-20 08:20 UTC by Vitalii2943

2024-03-20 08:20 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-20 09:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-21 09:29 UTC, koalex requested changes
По 7-2 скинул в дискорд

2024-03-22 09:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-24 07:05 UTC, koalex requested changes
по 7-4 скинул в дискорд файл с замечаниями

2024-03-24 09:38 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-24 10:25 UTC, koalex approved these changes

2024-03-24 10:26 UTC, merged